
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";

export const CONFIRMED_ORDER_REQUEST = "CONFIRMED_ORDER_REQUEST";
export const CONFIRMED_ORDER_SUCCESS = "CONFIRMED_ORDER_SUCCESS";
export const CONFIRMED_ORDER_FAILURE = "CONFIRMED_ORDER_FAILURE";

export const PLACED_ORDER_REQUEST = "PLACED_ORDER_REQUEST";
export const PLACED_ORDER_SUCCESS = "PLACED_ORDER_SUCCESS";
export const PLACED_ORDER_FAILURE = "PLACED_ORDER_FAILURE";

export const SHIPPED_ORDER_REQUEST = "SHIPPED_ORDER_REQUEST";   
export const SHIPPED_ORDER_SUCCESS = "SHIPPED_ORDER_SUCCESS";
export const SHIPPED_ORDER_FAILURE = "SHIPPED_ORDER_FAILURE";

export const DELIVERED_ORDER_REQUEST = "DELIVERED_ORDER_REQUEST";
export const DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS";
export const DELIVERED_ORDER_FAILURE = "DELIVERED_ORDER_FAILURE";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";






